### ISSUE TITLE
Conio example is broken

### ISSUE THREAD

**Issue by gyrovorbis** [KallistiOS/KallistiOS#98]
The Conio example is broken in two different ways and has been ever since KOS2. I intend to fix it, but I have a lot of stuff I'd like to get around to first, and this is also a nice task for someone looking to make a contribution to KOS.

1) We've verified that ever since KOS2, with any toolchain/GCC version, the example didn't work and gives some kind of warning on thread initialization about using a deprecated path that I'm assuming has changed. It will build with the older toolchains (4.7.4 and 9.3.0), but it's a black screen and doesn't do anything.

2) Secondly, there is just absolutely NO WAY that this is a valid C program. The new GCC12 toolchain RIGHTFULLY doesn't even compile it. It has a whole common header of dozens and dozens of variable declarations which are not extern, getting included everywhere, and duplicated in each translation unit, causing duplicate symbol errors... I have no earthly idea what the older GCC versions were doing letting this slide, but it's not correct. 

Somebody needs to fix the threading then declare the variables within the common header extern, copying the existing definitions from the header into only a single translation unit, deduplicating the symbols.

**Comment by andressbarajas** [comment]
I'll give it a go.  Been a while since I touched C and Dreamcast development.  Can't say I will be fast but hopefully it get done.

**Comment by gyrovorbis** [comment]
Awesome, man!! This one's a classic, I'd hate to see it just stay broken, haha.

**Comment by andressbarajas** [comment]
https://github.com/KallistiOS/kos-ports/pull/19 to fix missing graphics.  

https://github.com/andressbarajas/libconio I made changes here to fix thread initialization.  Changes need to be committed to 
https://sourceforge.net/p/cadcdev/libconio/ci/master/tree/

**Comment by andressbarajas** [comment]
https://github.com/KallistiOS/KallistiOS/pull/100 Fix Adventure example compile errors.

Pull request 100! Woot Woot
