### PR TITLE
Update patch for building GCC 12.2.0 toolchain on macOS

### PR DESCRIPTION
**Pull request by darcagn**

### CODE REVIEW

**Comment by DC-SWAT** [comment]
Also binutils fails with iconv, but I have in installed.

`configure: WARNING:
*** Makeinfo is too old. Info documentation will not be built.
checking for expect... (cached) /usr/bin/expect
checking for Tcl supporting try/catch... (cached) no
checking for linker versioning flags... (cached) -export-symbols-regex ctf_.*
checking that generated files are newer than configure... done
configure: creating ./config.status
  CC       dw2gencfi.o
  CC       ecoff.o
  CC       ehopt.o
  CC       expr.o
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
  CC       flonum-copy.o
  CC       frags.o
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CCLD     libctf.la
  CC       gen-sframe.o
libtool: link: warning: `-version-info/-version-number' is ignored for convenience libraries
  CC       hash.o
  CC       input-file.o
  CC       input-scrub.o
  CC       listing.o
  CC       literal.o
  CC       macro.o
  CC       messages.o
  CC       output-file.o
  CC       read.o
  CC       remap.o
  CC       sb.o
  CC       sframe-opt.o
  CC       stabs.o
  CC       subsegs.o
  CC       symbols.o
  CC       write.o
  CC       config/tc-sh.o
  CC       config/obj-elf.o
  CC       config/atof-ieee.o
  CCLD     as-new
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_iconv_close", referenced from:
      __nl_free_domain_conv in libintl.a(loadmsgcat.o)
  "_iconv_open", referenced from:
      __nl_init_domain_conv in libintl.a(loadmsgcat.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [as-new] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-gas] Error 2
make[1]: *** [all] Error 2
make: *** [build-sh4-binutils] Error 1`

**Comment by gyrovorbis** [comment]
We just saw this comment and are checking on it. We have had several people successfully build for Mac, but we see you're on Intel and they may have all been m1... Let me try this on my Intel Mac then... 

Huge fan of your work, by the way, hoping the new toolchain yields performance and binary size improvements for you!

**Comment by DC-SWAT** [comment]
> We just saw this comment and are checking on it. We have had several people successfully build for Mac, but we see you're on Intel and they may have all been m1... Let me try this on my Intel Mac then...

Yes on Intel CPU.

> Huge fan of your work, by the way, hoping the new toolchain yields performance and binary size improvements for you!
I hoping too :) It's very important for loaders.
Build with binutils 2.34 yet and will test thanks!

**Comment by andressbarajas** [comment]
Builds fine for me.  2016 Intel Mac Book pro

**Comment by DC-SWAT** [comment]
I use MacBook Pro 2019 model A2141
